BACKGROUND = "#ffd13c"
BUTTON_NORMAL = "#ffbb00"
BUTTON_SELECTED="#ffd13c"
BUTTON_CLICKED="#ffcc24"
TEXT_COLOR = "#000000"

SCROLL_BACKGROUND = "#ffbb00"
SCROLL_TROUGH= "#ffd13c"
SCROLL_BORDER= "#ffd13c"
SCROLL_ARROW= "#f8ec48"

TITLE_FONT = ("Pixelon", 14)
TEXT_FONT = ("Pixelon", 10)

##CONTANTS
WINDOW_WIDTH = 250
WINDOW_HEIGHT = 200

CENTER_X = WINDOW_WIDTH // 2
CENTER_Y = WINDOW_HEIGHT // 2